#!/bin/sh

shellcheck
sudo mv configuration.nix configuration.nix.old && sudo wget https://raw.githubusercontent.com/teknostatik/nixos/master/configuration.nix
sudo nixos-rebuild test
sudo nixos-rebuild switch

